// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc019nVsZ7iq6JrYUimlomy31kuQDBSN8',
    appId: '1:673071391218:web:707ab8ae30fd4bee648b6b',
    messagingSenderId: '673071391218',
    projectId: 'watches1',
    authDomain: 'watches1.firebaseapp.com',
    storageBucket: 'watches1.appspot.com',
    measurementId: 'G-XVMLWMDL3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxjabQbynM74gw8xaQEwtnR-EzyTzock',
    appId: '1:673071391218:android:04345a2b1c7d4db6648b6b',
    messagingSenderId: '673071391218',
    projectId: 'watches1',
    storageBucket: 'watches1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpGDP0xnwljCVzcWRsGVtWxCDzZ21Aus',
    appId: '1:673071391218:ios:f5245563a1b7a15f648b6b',
    messagingSenderId: '673071391218',
    projectId: 'watches1',
    storageBucket: 'watches1.appspot.com',
    iosBundleId: 'com.example.amigurumiArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrpGDP0xnwljCVzcWRsGVtWxCDzZ21Aus',
    appId: '1:673071391218:ios:f5245563a1b7a15f648b6b',
    messagingSenderId: '673071391218',
    projectId: 'watches1',
    storageBucket: 'watches1.appspot.com',
    iosBundleId: 'com.example.amigurumiArt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc019nVsZ7iq6JrYUimlomy31kuQDBSN8',
    appId: '1:673071391218:web:36643b568fe84a9a648b6b',
    messagingSenderId: '673071391218',
    projectId: 'watches1',
    authDomain: 'watches1.firebaseapp.com',
    storageBucket: 'watches1.appspot.com',
    measurementId: 'G-S3SWYS1DEQ',
  );
}
